<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Полезные ссылки</title>
    </head>

    <body>

<H1>Полезные ссылки:</H1>
    <br><br>
    <a href="http://htmlbook.ru/html/type/table">Хороший справочник по HTML - тэгам</a>
    <br><br>
    <a href="https://csscolor.ru/">Подобрать цвет онлайн</a>
    <br><br>
    <a href="https://translate.yandex.by/">Яндекс - переводчис</a>

    <br><br><br><br>

    <H3><a href="/main">go to   Main page</a></H3>

    </body>
</html>