<!DOCTYPE html>
<html lang="ru">

    <head>
        <meta charset="UTF-8">
        <title>Магазины ДОБРОЦЕН, нанесенные на Яндекс.Карты</title>
        <link rel="stylesheet" href="css/style.css">

    </head>

    <body>

        Магазины на Яндекс - карте:
        <div id="map" class="map"></div>

        <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript">
        </script>
        <script src="shops_map.js" type="text/javascript"></script>
        <#--<script src="main.js" type="text/javascript"></script>-->
    </body>

</html>